import type { NextPage } from "next";
import { useRouter } from "next/router";

import Head from "next/head";
import EmailList from "../components/EmailList";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { useContext, useEffect, useState } from "react";
import { auth } from "../config/firebase";
import { IUser } from "../Interfaces/Interfaces";
import Login from "../components/Login";
import { AuthContext } from "../context/AuthContext";
import ComposeEmail from "../components/ComposeEmail";
import { useRecoilState, useRecoilValue } from "recoil";
import { modalState } from "../atoms/modalAtoms";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  const router = useRouter();
  const user = useContext(AuthContext);
  const [composeEmail] = useRecoilState<boolean>(modalState);

  if (!user) return <Login />;

  return (
    <div className="w-screen h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-row">
        <Sidebar />
        <EmailList />
      </main>
      {composeEmail && <ComposeEmail />}
      <Footer />
    </div>
  );
};

export default Home;
